name: My first Github workflow
run-name: First workflow # Optional

# Events triggering workflow
on: [push]

# Group of jobs to run as part of the workflow
jobs:
  greet:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Hello world"